// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetMatchHistoryHeroesByIds(arg1:Array<number>):Promise<Record<number, types.HeroInfo>>;

export function GetMatchHistoryNameAndIconByHeroId(arg1:number):Promise<types.HeroInfo>;

export function GetPlayerRankMatches(arg1:string):Promise<types.MatchHistory>;
