// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetGameDetail(arg1:number,arg2:string):Promise<types.GameDetail>;
