// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMatchHistoryHeroesByIds(arg1) {
  return window['go']['controller']['MatchHistory']['GetMatchHistoryHeroesByIds'](arg1);
}

export function GetMatchHistoryNameAndIconByHeroId(arg1) {
  return window['go']['controller']['MatchHistory']['GetMatchHistoryNameAndIconByHeroId'](arg1);
}

export function GetPlayerRankMatches(arg1) {
  return window['go']['controller']['MatchHistory']['GetPlayerRankMatches'](arg1);
}
