// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlayerRankData(arg1) {
  return window['go']['controller']['PlayerController']['GetPlayerRankData'](arg1);
}
