// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImgSrc(arg1) {
  return window['go']['main']['App']['GetImgSrc'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RiotPort() {
  return window['go']['main']['App']['RiotPort']();
}

export function RiotToken() {
  return window['go']['main']['App']['RiotToken']();
}
