// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentChampSelectSnapshot() {
  return window['go']['main']['App']['GetCurrentChampSelectSnapshot']();
}

export function GetImgSrc(arg1) {
  return window['go']['main']['App']['GetImgSrc'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
