// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {diag} from '../models';

export function GetCurrentChampSelectSnapshot():Promise<types.ChampSelectSnapshot>;

export function GetCurrentSummoner():Promise<types.IPlayerBaseData>;

export function GetDiagnostics():Promise<diag.Snapshot>;

export function GetImgSrc(arg1:number):Promise<string>;

export function GetMyCareer():Promise<types.TeamMemberSummary>;

export function GetPositionIcon(arg1:string):Promise<string>;

export function GetRankEmblem(arg1:string):Promise<string>;

export function OpenLogDir():Promise<void>;
