// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function GetCurrentChampSelectSnapshot():Promise<types.ChampSelectSnapshot>;

export function GetCurrentSummoner():Promise<types.IPlayerBaseData>;

export function GetImgSrc(arg1:number):Promise<string>;
